name: flutter_modular_architecture_main
description: It is a main project
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  shell:
    git: https://github.com/MuhammedAlmaz/flutter_modular_architecture_shell.git
  account:
    git: https://github.com/MuhammedAlmaz/flutter_modular_architecture_account.git
  loan:
    git: https://github.com/MuhammedAlmaz/flutter_modular_architecture_loan.git
  payment:
    git: https://github.com/MuhammedAlmaz/flutter_modular_architecture_payment.git
  transfer:
    git: https://github.com/MuhammedAlmaz/flutter_modular_architecture_transfer.git

flutter:

  uses-material-design: true